### PR TITLE
pull request de las tildes

### PR DESCRIPTION
**Pull request by Rafael2432**
Se acaban de agregar tildes.

### CODE REVIEW

**Comment by Rafael2432** [comment]
something is missing

**Comment by robertoElDinosaurio123** [comment]
change the typo error with html labels

**Comment by robertoElDinosaurio123** [comment]
**ok, everything is all right 

> now**_

1. @

_

**Review by robertoElDinosaurio123 — CHANGES_REQUESTED** [review]
do not send ANYTHING!

**Review by robertoElDinosaurio123 — APPROVED** [review]
all right dude, do the merge

**Review by robertoElDinosaurio123 — CHANGES_REQUESTED** [review]
bullshit, cancelled it right now

**Review by robertoElDinosaurio123 — CHANGES_REQUESTED** [review]
sorry dude, i get confused

**Review by robertoElDinosaurio123 — COMMENTED** [review]
just do it

**Review by robertoElDinosaurio123 — APPROVED** [review]
do it now

**Pull request merged**
